### ISSUE TITLE
The idea of full-frames attention shares a great similarity with the spatial-temporal modeling approach used in Vid2Vid-Zeros.

### ISSUE THREAD

**Issue by jinxixiang** [YBYBZhang/ControlVideo#11]
If I could be wrong, the full-frame attention is similar to https://github.com/baaivision/vid2vid-zero.

**Comment by YBYBZhang** [comment]
Thanks for your attention! We're sorry that we hadn't noticed this concurrent paper before, since recently there are a large amount of video-related papers :)
After reading vid2vid-zero, we observe that there are three main differences in cross-frame mechanisms between our ControlVideo and vid2vid-zero:
1. ControlVideo applys fully cross-frame in all attention modules of SD, while vid2vid-zero uses both fully and sparse cross-frame in different attention modules.
2. ControlVideo is the first to apply fully cross-frame in controllable text-to-video generation, whereas vid2vid-zero is designed for video editing task.
3. Experiments in our paper provide more insights on fully cross-frame, _i.e._, showing higher video quality and temporal consistency in large motion videos.

**Comment by jinxixiang** [comment]
thank you for your elaborate response.

**Comment by jinxixiang** [comment]
I have also assessed the performance of depth control in comparison to two comparable video generation studies on MSRVTT dataset.  

resolution at 256*256

videocomposer (https://github.com/damo-vilab/videocomposer)
{"fid50k_full": 32.85220698351932} {"fvd2048_16f": 292.60702360087384}

controlvideo (https://github.com/YBYBZhang/ControlVideo)
{"fid50k_full": 53.00012164453821}, {"fvd2048_16f": 716.0677660664312}

control-a-video (https://github.com/Weifeng-Chen/control-a-video)
{"fid50k_full": 43.23543254253663} {"fvd2048_16f": 339.1774903700448}
