### ISSUE TITLE
Is the same frame noise important?

### ISSUE THREAD

**Issue by CHNxindong** [YBYBZhang/ControlVideo#30]
Thanks for your great work! 
I notice the prepare_latents function in pipeline_controlvideo.py makes the frame noise same: 
![image](https://github.com/YBYBZhang/ControlVideo/assets/20262070/b7ab0a6b-40b7-4680-a2fd-90ef17739c4c) 

But the frame noise in Vid2vid-zero, Tune-A-Video are individually generated (the noises are different among frames):
![image](https://github.com/YBYBZhang/ControlVideo/assets/20262070/87caed9c-3dfe-434c-8003-cbf49231d994) 

Thus I want to know wheather the same frame noise is important for your great results?
Thank you!

**Comment by YBYBZhang** [comment]
Thanks for your attention on our work! From my experience, the same frame noise may slightly improve temporal consistency in ControlVideo, since the motion of generated video comes from structure sequence (e.g., depth maps).
In contrast, Tune-A-Video and Vid2Vid-Zero rely on DDIM inversion latent codes to inherit motion, so their initial noises cannot be same.

**Comment by CHNxindong** [comment]
I see. Thanks for your reply!
