### ISSUE TITLE
smoother_step

### ISSUE THREAD

**Issue by dlutzzw** [YBYBZhang/ControlVideo#8]
hi, I restart a new issue, because I'm also confused about the timesteps of interleaved-frame smoother. The paper says that : "interleaved-frame smoother is performed on predicted RGB frames at timesteps {30, 31} by default" , But your code use 19, 20 as default. How is this parameter determined， Why not do smoother on all DDIM steps？Have you done ablation for this part of the experiment? I don't seem to see it in the paper.

**Comment by YBYBZhang** [comment]
1. Since DDIM inverison (50 steps in total) starts from t=50 to t=0, and {30,31}  claimed in paper is indices and actually corresponds to {50-30, 50-31}={20,19} timesteps. We will fix it in our paper.
2. In our experiments, 2 or 4 steps are enough to smooth the video, and using more will increase the time cost. We have put all ablation results on smoother in our appendix, which will be public later.
